# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CriaMemorial
                                 A QGIS plugin
 Teste de desenvolvimento para criação de memoriais de loteamento
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-07-30
        copyright            : (C) 2026 by Eduardo C. Siqueira
        email                : eduardo.edu28@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CriaMemorial class from file CriaMemorial.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .cria_memorial import CriaMemorial
    return CriaMemorial(iface)
