# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CriaMemorial
                                 A QGIS plugin
 Teste de desenvolvimento para criação de memoriais de loteamento
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-07-30
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Eduardo C. Siqueira
        email                : eduardo.edu28@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QLocale, QTranslator, QCoreApplication
from qgis.core import Qgis, QgsWkbTypes, QgsSettings, QgsProject, QgsMapLayerType 
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction


# Import the code for the dialog
from .lixeira.cria_memorial_dialog import CriaMemorialDialog
from .lixeira.teste_dialog import TesteDialog
from .lixeira.teste_dinamico_dialog import TesteDinamicoDialog
from .dialogs.general_info_dialog import GeneralInfoDialog
from .dialogs.basic_parcels_wizard import BasicParcelsWizard
from .dialogs.main_parcel_dialog import MainParcelDialog
# from .basic_parcel_dialog import BasicParcelDialog

from .models.memorial_padrao_loteamento import MemorialPadraoLoteamento
from .models.full_parcel import FullParcel
from .models.basic_parcel import BasicParcel
from .models.complements import Side, Front, Segment, Street
from .models.data_classes import GeneralInfoObject
from .utils.db_manager import DataBaseManager
from .processing import filter_polygon_features

import os.path


class CriaMemorial:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QgsSettings().value('locale/userLocale', QLocale().name())[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            '{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Criação Memorial Teste')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('CriaMemorial', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = os.path.join(os.path.dirname(__file__), 'icon.png')
        self.add_action(
            icon_path,
            text=self.tr(u'Criar memorial'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Criação Memorial Teste'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.db_manager = DataBaseManager()

        #loads from DB
        self.general_info: GeneralInfoObject = self.db_manager.get("general_info")
        self.parcels: list[BasicParcel] = self.db_manager.get("parcels") or []
        self.main_parcel_name = self.db_manager.get("main_parcel_name")

        project = QgsProject.instance()        
        general_info_dialog = GeneralInfoDialog()

        if self.general_info:
            general_info_dialog.pre_set(self.general_info)
        
        general_info_dlg_result = general_info_dialog.exec_()
        if general_info_dlg_result:
            self.db_manager.update("general_info", general_info_dialog.as_general_info_object())

        feature_list = filter_polygon_features(project)
        parcel_definition_wizard = BasicParcelsWizard(feature_list)
        parcel_definition_result = parcel_definition_wizard.exec_()
        if parcel_definition_result:
            for result in parcel_definition_wizard.get_results():
                self.parcels.append(
                    BasicParcel(
                        result["parcel_name"],
                        result["block"],
                        result["site_plan"],
                        result["site_plan_code"],
                        result["feature_context"]
                    )
                )
            self.db_manager.update("parcels", self.parcels)
            self.main_parcel_name = parcel_definition_wizard.get_main_parcel_name()
            self.db_manager.update("main_parcel_name", self.main_parcel_name)

        selected_parcel = next((parcel for parcel in self.parcels if parcel.name == self.main_parcel_name), None)
        print(f"""Lote selecionada como principal:
        Nome: {selected_parcel.name}
        Quadra: {selected_parcel.block}
        Planta: {selected_parcel.site_plan_name}""")
        main_parcel_dialog = MainParcelDialog(selected_parcel)
        main_parcel_dialog_result = main_parcel_dialog.exec_()
        # self.test()

    def capture_polygons(self, project):
        # capture the project's polygons
        polygon_layers = {
            layer 
            for layer in project.mapLayers().values() 
            if layer.type() == QgsMapLayerType.VectorLayer
            and layer.geometryType() == QgsWkbTypes.PolygonGeometry
            }
        print("capture the polygons in each layer and verifies multiPolygons")
        polygons = []
        multi_polygons = []
        for layer in polygon_layers:
            for feature in layer.getFeatures():
                geom = feature.geometry()
                if geom.type() == Qgis.GeometryType.Polygon:
                    print("Encontrado multiPolígono")
                    geom_collection = geom.asGeometryCollection()
                    if len(geom_collection) == 1:
                        print("Encontrado multiPolígono com 1 elemento")
                        polygons.append({
                                "name": f"{layer.name()} {str(feature.id()) if layer.featureCount()>1 else ''}",
                                "geom": geom_collection[0]
                                })
                    elif len(geom_collection) > 1:
                        print("Encontrado multipoligono com mais de 1 elemento")
                        multi_polygons.append(geom)

        print("\nPolígonos únicos encontrados:")
        for polygon in polygons:
            print("Polígono:", polygon["name"], polygon["geom"].asWkt())
        if len(multi_polygons)>0:
            print("aviso! Encontrados Multipolígonos!")
        else:
            print("Nenhum MultiPolígono encontrado!")
        print("end of phase1")
        return polygons

    def project_polygons_to_parcels(self, project: QgsProject) -> list[BasicParcel]:
        result_list = []
        polygon_layers = {
            layer 
            for layer in project.mapLayers().values() 
            if layer.type() == QgsMapLayerType.VectorLayer
            and layer.geometryType() == QgsWkbTypes.PolygonGeometry
            }
        for layer in polygon_layers:
            for feature in layer.getFeatures():
                geom = feature.geometry()
                if geom.type() == Qgis.GeometryType.Polygon:
                    if geom.isMultipart():
                        collection = geom.asGeometryCollection()
                        if len(collection) > 1:
                            # process_multi_part()
                            print("Multipolígono Encontrado!")
                        elif len(collection) == 1:
                            layer.selectByIds([feature.id()])
                            dlg = BasicParcelDialog()
                            if dlg.exec_():
                                parcel = BasicParcel(
                                    dlg.get_text_input_result("nome1"),
                                    dlg.get_text_input_result("quadra1"),
                                    dlg.get_text_input_result("planta1"),
                                    dlg.get_text_input_result("cod_planta1"),
                                    collection[0]
                                )
                                result_list.append(parcel)
                                    
        return result_list

    def test(self):
        main_parcel = FullParcel(
                    "default_name",
                    "default_block",
                    "default_site_plan",
                    None,
                    None,
                    "default_district",
                    "par",
                    Street("default_front_street_name", None),
                    "default_number",
                    "regular",
                    "default_distance_to_corner",
                    Street("default_corner_street", None),
                    "default_area",
                    "default_porperty_identifier",
                    Front("default_front_name", [Segment(1,"default_front_measure","default_front_confrontations")],Street("default_front_street_name", None)),
                    True,
                    [Side("default_side1",[Segment(1,"default_side1_measure","default_side1_confrontations")]),Side("default_side2",[Segment(1,"default_side2_measure","default_side2_confrontations")]),Side("default_side3",[Segment(1,"default_side3_measure","default_side3_confrontations")])]
                    )
        memorial = MemorialPadraoLoteamento("default_stamp", "default_arquitect", "Masculino", "default_CAU", main_parcel)
        general_info_dialog = GeneralInfoDialog()
        project = QgsProject.instance()

        general_info_dlg_result = general_info_dialog.exec_()
        if general_info_dlg_result:
            print(f"""
                MEMORIAL DESCRITIVO DO {general_info_dialog.stamp}
            Quadra: {general_info_dialog.block}
            Planta: {general_info_dialog.site_plan},
            Bairro: {general_info_dialog.block}
            IF: {general_info_dialog.property_identifier}
            Arquitet{"a" if general_info_dialog.arquitect_gender == "Feminino" else "o"}: {general_info_dialog.arquitect}
            Genero: {general_info_dialog.arquitect_gender}
            """)
            main_parcel.district = general_info_dialog.block
            main_parcel.property_identifier = general_info_dialog.property_identifier
            memorial.arquitetx = general_info_dialog.arquitect
            memorial.cau = general_info_dialog.cau_code
            memorial.titulo_carimbo = general_info_dialog.stamp
            memorial.genero_arquitetx = general_info_dialog.arquitect_gender

        parcel_list = self.project_polygons_to_parcels(project)
        # TODO: desenvolver dialog de seleção do lote
        # TODO: desenvolver separação dos lados e vertices para posterior seleção
        # TODO: desenvolver dialog de definição de lados
        # TODO: desenvolver dialog para informações complementares do lote principal

        #TODO: código de teste a ser deletado após resolução
        first_parcel = parcel_list[0]
        main_parcel.block = first_parcel.block
        main_parcel.site_plan_name = first_parcel.site_plan_name
        main_parcel.name = first_parcel.name
        main_parcel.site_plan_code = first_parcel.site_plan_code
        print(memorial.geraMemorial())

        # polygons = self.capture_polygons(project)

        # dinamic_dlg = TesteDinamicoDialog(polygon_list=polygons)
        # dinamic_dlg.show()
        # dinamic_result = dinamic_dlg.exec_()
        # print("Resultado", dinamic_result)

        # if dinamic_result:
        #     for polygon in polygons:
        #         polygon["name"] = dinamic_dlg.polygon_dict[polygon["name"]].text()
        # print("Lista atualizada:", polygons)

        # new_dinamic_dlg = TesteDinamicoDialog(polygon_list=polygons)
        # new_dinamic_dlg.show()
        # new_dinamic_dlg.exec_()

        
        
        # # show the dialog
        # self.dlg.mMapLayerComboBox.setFilters(Qgis.LayerFilter.PolygonLayer)
        # self.dlg.show()
        # # Run the dialog event loop
        # result = self.dlg.exec_()
        # # See if OK was pressed
        # if result:

            # captura projeto e lista as mapLayers
            # listar todos os polígonos, e verificar se existe multipolígono
            # nomeia todos os polígonos tranformando em loteBasico
            # pergunta qual o lote principal e o tipo de memorial + informações complementares do lote principal
            
            ## LOTEAMENTO 


            # print("Camada selecionada: ", self.dlg.mMapLayerComboBox.currentLayer().name())
            # print("Botão funcionando aindaaaaaaaaaaaaaaa")
            

            # for layer_id, layer in project.mapLayers().items():
            #     print(layer.name, layer_id)
                
            # activeLayer = self.iface.activeLayer()

            # print("Camada ativa: " + activeLayer.name())

            # camadaVertice = project.mapLayersByName("Vértices")[0]

            # print("Camada Vértice: " + camadaVertice.name())

            # for feat in camadaVertice.getFeatures():
            #     print(f"Feição: {feat.id()}")
            #     print(f"Atributos: {feat.attributes()}")
            #     for i, v in enumerate(feat.geometry().vertices()):
            #         print(f"Vértice {i}: ({v.x()}, {v.y()})")

        # self.dlg2.show()