# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CriaMemorial
                                 A QGIS plugin
 Teste de desenvolvimento para criação de memoriais de loteamento
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-07-30
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Eduardo C. Siqueira
        email                : eduardo.edu28@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QLocale, QTranslator, QCoreApplication
from qgis.core import QgsSettings, QgsProject
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction


# Import the code for the dialog
from .dialogs.show_result_dialog import ShowResultDialog
from .dialogs.cancel_dialog import CancelDialog

from .models.memorial_padrao_base import MemorialPadraoBase
from .models.memorial_padrao_loteamento import MemorialPadraoLoteamento
from .processing import (
    process_general_info_dialog, 
    process_parcel_definition,
    process_main_parcel_dialog,
    process_sides_definition,
    process_confrontation_definition
)

import os.path


class CriaMemorial:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QgsSettings().value('locale/userLocale', QLocale().name())[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            '{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Criação Memorial Teste')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('CriaMemorial', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = os.path.join(os.path.dirname(__file__), 'icon.png')
        self.add_action(
            icon_path,
            text=self.tr(u'Criar memorial'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Criação Memorial Teste'),
                action)
            self.iface.removeToolBarIcon(action)

    def run(self):
        """Run method that performs all the real work"""

        if self.first_start == True:
            self.first_start = False
            self.general_info = None
            self.cancel_dialog = CancelDialog()
        
        self.project = QgsProject.instance()
        self.create_memorial_p_loteamento()

    def create_memorial_p_loteamento(self):

        result_step_1 = process_general_info_dialog(self.general_info)
        if result_step_1 is not None:
            self.general_info = result_step_1
        else:
            self.cancel_dialog.exec_()
            return

        result_step_2 = process_parcel_definition(self.iface, self.project)
        if result_step_2 is not None:
            selected_parcel, other_parcels = result_step_2
        else:
            self.cancel_dialog.exec_()
            return

        result_step_3 = process_main_parcel_dialog(selected_parcel)
        if result_step_3 is not None:
            self.main_parcel = result_step_3
        else:
            self.cancel_dialog.exec_()
            return

        if self.memorial is None:
            self.memorial = MemorialPadraoLoteamento(
                MemorialPadraoBase(self.general_info), 
                self.main_parcel, 
                other_parcels
            )
        else:
            self.memorial.main_parcel = self.main_parcel
            self.memorial.other_parcels = other_parcels

        result_step_4 = process_sides_definition(self.iface, self.project, self.memorial.main_parcel)
        if result_step_4 is False:
            self.cancel_dialog.exec_()
            return

        result_step_5 = process_confrontation_definition(self.memorial.main_parcel)
        if result_step_5:
            #Processa criação de memorial
            print(self.memorial.geraMemorial())
            final_result_dlg = ShowResultDialog(self.memorial.geraMemorial())
            final_result_dlg.exec_()
        else:
            self.cancel_dialog.exec_()
            return