# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CriaMemorialDialog
                                 A QGIS plugin
 Teste de desenvolvimento para criação de memoriais de loteamento
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-07-30
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Eduardo C. Siqueira
        email                : eduardo.edu28@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from PyQt5.QtCore import QMetaType
from qgis.core import QgsField, QgsPalLayerSettings, QgsVectorLayerSimpleLabeling, Qgis
from .bpw_first_page import BPWFirstPage
from .bpw_input_page import BPWInputPage
from .bpw_last_page import BPWLastPage
from ..models.data_classes import FeatureContext

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(
    os.path.join(
        os.path.dirname(__file__),
        'basic_parcels_wizard_base.ui'),
    from_imports=True,
    import_from='cria_memorial')

#TODO: Configurar para ignorar não preenchidos?
class BasicParcelsWizard(QtWidgets.QWizard, FORM_CLASS):
    def __init__(self, feature_contexts: list[FeatureContext], parent=None):
        """Constructor."""
        super(BasicParcelsWizard, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.feature_contexts = feature_contexts
        self.layers = set([feature_context.layer for feature_context in feature_contexts])
        self.prepare_layers()
        self.update_features()
        self.setupUi(self)
        self.input_pages: list[BPWInputPage] = []
        self.next_button = self.button(QtWidgets.QWizard.NextButton)
        self.next_button.setDefault(True)
        self.setButtonText(QtWidgets.QWizard.CustomButton1, "Ir para o fim")
        self.populate()
        self.rejected.connect(self.quit)
        self.accepted.connect(self.finish)
        self.currentIdChanged.connect(self.on_page_changed)
        self.customButtonClicked.connect(self.on_custom_button_clicked)

    def populate(self):
        self.removePage(1)
        self.removePage(0)
        self.addPage(BPWFirstPage())
        for feature_context in self.feature_contexts:
            new_page = BPWInputPage(feature_context)
            self.addPage(new_page)
            if feature_context.layer.fields().indexOf("nome_lote") != -1:
                parcel_name = feature_context.feature["nome_lote"]
                if parcel_name:
                    new_page.set_parcel_name(str(parcel_name))
            self.input_pages.append(new_page)
        self.addPage(BPWLastPage())


    def get_results(self):
        result_list = []
        for pageId in self.pageIds()[1:-1]:
            result_list.append(self.page(pageId).get_values())
        return result_list

    def get_main_parcel_name(self):
        last_page = self.page(self.pageIds()[-1])
        return last_page.selected_parcel_name

    def prepare_layers(self):
        # prepara a camada para receber o nome do lote como atributo e exibir como label
        for layer in self.layers:
            fields = layer.fields()
            layer.startEditing()
            if fields.indexOf("nome_lote") == -1:
                if layer.addAttribute(QgsField("nome_lote", QMetaType.Type.QString)):
                    print("Atributo adicionado")
                    layer.updateFields()
                else:
                    print("Falha ao criar atributo")
            settings = QgsPalLayerSettings()
            settings.fieldName = "nome_lote"
            settings.placement = Qgis.LabelPlacement.OverPoint
            layer.setLabeling(QgsVectorLayerSimpleLabeling(settings))
            layer.setLabelsEnabled(True)

    def quit(self):
        self.clean_highlights()
        for fc in self.feature_contexts:
            fc.layer.rollBack()

    def finish(self):

        self.clean_highlights
        for fc in self.feature_contexts:
            fc.layer.commitChanges()

    def clean_highlights(self):

        for layer in self.layers:
            layer.removeSelection()
    
    def update_features(self):

        for fc in self.feature_contexts:
            id = fc.feature.id()
            fc.feature = fc.layer.getFeature(id)

    def on_page_changed(self):

        self.clean_highlights()
        page = self.currentPage()
        if isinstance(page, BPWInputPage):
            page.feature_context.layer.select(
                page.feature_context.feature.id()
            )
        self.next_button.setDefault(True)

    def on_custom_button_clicked(self, which):

        if which == QtWidgets.QWizard.CustomButton1:
            while self.nextId() != -1:
                self.next()