# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CriaMemorialDialog
                                 A QGIS plugin
 Teste de desenvolvimento para criação de memoriais de loteamento
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-07-30
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Eduardo C. Siqueira
        email                : eduardo.edu28@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from ..utils.dialog_builder import create_label_qline_pairs, add_label_qline_pairs_to_qvbox

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(
    os.path.join(
        os.path.dirname(__file__),
        'basic_parcel_dialog_base.ui'),
    from_imports=True,
    import_from='cria_memorial')


class BasicParcelDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, number_of_parcels=1, parent=None):
        """Constructor."""
        super(BasicParcelDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.text_input_dict = {}
        self.populate(number_of_parcels)
        

    def populate(self, number_of_parcels: int):
        if number_of_parcels>1:
            for i in range(number_of_parcels):
                create_label_qline_pairs({
                    f"nome{i+1}": f"NOME DO LOTE ({i+1})",
                    f"quadra{i+1}": f"QUADRA ({i+1})",
                    f"planta{i+1}": f"PLANTA ({i+1})",
                    f"cod_planta{i+1}": f"CÓDIGO DA PLANTA ({i+1})"
                    }, 
                    self.text_input_dict)
        else:
            create_label_qline_pairs({
                f"nome1": f"NOME DO LOTE:",
                f"quadra1": f"QUADRA:",
                f"planta1": f"PLANTA:",
                f"cod_planta1": f"CÓDIGO DA PLANTA:"
                }, 
                self.text_input_dict)
        add_label_qline_pairs_to_qvbox(self.verticalLayout, self.text_input_dict)

    def get_text_input_result(self, key: str):
        return self.text_input_dict[key]["input"].text()