# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CriaMemorialDialog
                                 A QGIS plugin
 Teste de desenvolvimento para criação de memoriais de loteamento
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-07-30
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Eduardo C. Siqueira
        email                : eduardo.edu28@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from .bpw_first_page import BPWFirstPage
from .bpw_input_page import BPWInputPage
from .bpw_last_page import BPWLastPage
from ..models.data_classes import FeatureContext

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(
    os.path.join(
        os.path.dirname(__file__),
        'basic_parcels_wizard_base.ui'),
    from_imports=True,
    import_from='cria_memorial')


class BasicParcelsWizard(QtWidgets.QWizard, FORM_CLASS):
    def __init__(self, feature_contexts: list[FeatureContext], parent=None):
        """Constructor."""
        super(BasicParcelsWizard, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.feature_contexts = feature_contexts
        self.setupUi(self)
        self.populate()
        self.rejected.connect(self.clean_highlights)

    def populate(self):
        self.removePage(1)
        self.removePage(0)
        self.addPage(BPWFirstPage())
        for feature_context in self.feature_contexts:
            self.addPage(BPWInputPage(feature_context))
        self.addPage(BPWLastPage())

    def clean_highlights(self):
        for fc in self.feature_contexts:
            fc.layer.removeSelection()

    def get_results(self):
        result_list = []
        for pageId in self.pageIds()[1:-1]:
            result_list.append(self.page(pageId).get_values())
        return result_list

    def get_main_parcel_name(self):
        last_page = self.page(self.pageIds()[-1])
        return last_page.selected_parcel_name