# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CriaMemorialDialog
                                 A QGIS plugin
 Teste de desenvolvimento para criação de memoriais de loteamento
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-07-30
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Eduardo C. Siqueira
        email                : eduardo.edu28@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from ..models.data_classes import FeatureContext

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(
    os.path.join(
        os.path.dirname(__file__),
        'bpw_input_page_base.ui'),
    from_imports=True,
    import_from='cria_memorial')


class BPWInputPage(QtWidgets.QWizardPage, FORM_CLASS):
    def __init__(self, feature_context: FeatureContext, parent=None):
        """Constructor."""
        super(BPWInputPage, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.feature_context = feature_context
        self.setupUi(self)


    def get_values(self):
        return {
            "feature_context": self.feature_context,
            "parcel_name": self.parcel_name_lineEdit.text(),
            "block": self.block_lineEdit.text(),
            "site_plan": self.site_plan_lineEdit.text(),
            "site_plan_code": self.site_plan_code_lineEdit.text()
        }

    def set_values(self, parcel_name: str, block: str, site_plan: str, site_plan_code: str):
        self.parcel_name_lineEdit.setText(parcel_name)
        self.block_lineEdit.setText(block)
        self.site_plan_lineEdit.setText(site_plan)
        self.site_plan_code_lineEdit.setText(site_plan_code)

    def initializePage(self):
        self.wizard().clean_highlights()
        self.feature_context.layer.select(self.feature_context.feature.id())