# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CriaMemorialDialog
                                 A QGIS plugin
 Teste de desenvolvimento para criação de memoriais de loteamento
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-07-30
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Eduardo C. Siqueira
        email                : eduardo.edu28@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt.QtCore import Qt
from qgis.PyQt import QtWidgets
from .bpw_input_page import BPWInputPage

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(
    os.path.join(
        os.path.dirname(__file__),
        'bpw_last_page_base.ui'),
    from_imports=True,
    import_from='cria_memorial')


class BPWLastPage(QtWidgets.QWizardPage, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(BPWLastPage, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

    def initializePage(self):
        wizard = self.wizard()
        wizard.clean_highlights()

        # clear layout rows except first
        for row in range(self.gridLayout.rowCount() -1, 0, -1):
            for column in range(self.gridLayout.columnCount()-1, -1, -1):
                item = self.gridLayout.itemAtPosition(row, column)
                if item is not None:
                    widget = item.widget()
                    if widget is not None:
                        widget.deleteLater()
                        self.gridLayout.removeItem(item)

        #populate layout
        for index, pageId in enumerate(wizard.pageIds()[1:-1]):
            input_page:BPWInputPage = wizard.page(pageId)
            values = input_page.get_values()

            self.gridLayout.addWidget(QtWidgets.QLabel(values["parcel_name"]), index+1, 0, Qt.AlignTop)
            self.gridLayout.addWidget(QtWidgets.QLabel(values["block"]), index+1, 1, Qt.AlignTop)
            self.gridLayout.addWidget(QtWidgets.QLabel(values["site_plan"]), index+1, 2, Qt.AlignTop)
            self.gridLayout.addWidget(QtWidgets.QLabel(values["site_plan_code"]), index+1, 3, Qt.AlignTop)

            radio = QtWidgets.QRadioButton()
            radio.toggled.connect(self.manage_main_parcel_selection)
            self.gridLayout.addWidget(radio, index+1, 4, Qt.AlignTop)

    def manage_main_parcel_selection(self, checked):
        radio_button = self.sender()

        index = self.gridLayout.indexOf(radio_button)
        row, _, _, _ = self.gridLayout.getItemPosition(index)

        if checked:
            radio_button.setText("Lote principal")
            self.selected_parcel_name = self.gridLayout.itemAtPosition(row, 0).widget().text()
        else:
            radio_button.setText("")