# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CriaMemorialDialog
                                 A QGIS plugin
 Teste de desenvolvimento para criação de memoriais de loteamento
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-07-30
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Eduardo C. Siqueira
        email                : eduardo.edu28@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from ..models.data_classes import GeneralInfoObject

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(
    os.path.join(
        os.path.dirname(__file__),
        'general_info_dialog_base.ui'),
    from_imports=True,
    import_from='cria_memorial')


class GeneralInfoDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(GeneralInfoDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)


        self.prepare_inputs()
        self.populate()

    def prepare_inputs(self):
        self.text_input_dict = {
                            "stamp": {
                                "label": QtWidgets.QLabel("TÍTULO DO CARIMBO DA PRANCHA DE PROJETO DE LOTEAMENTO APROVADO:"),
                                "input": QtWidgets.QLineEdit()
                            },
                            "arquitect":{
                                "label": QtWidgets.QLabel("ARQUITETA/ARQUITETO:"),
                                "input": QtWidgets.QLineEdit()
                            },
                            "cau_code":{
                                "label": QtWidgets.QLabel("CAU:"),
                                "input": QtWidgets.QLineEdit()
                            },
                            "block":{
                                "label": QtWidgets.QLabel("QUADRA:"),
                                "input": QtWidgets.QLineEdit()
                            },
                            "site_plan":{
                                "label": QtWidgets.QLabel("PLANTA:"),
                                "input": QtWidgets.QLineEdit()
                            },
                            "site_plan_code":{
                                "label": QtWidgets.QLabel("CÓDIGO DA PLANTA:"),
                                "input": QtWidgets.QLineEdit()
                            },
                            "district":{
                                "label": QtWidgets.QLabel("BAIRRO:"),
                                "input": QtWidgets.QLineEdit()
                            },
                            "property_identifier":{
                                "label": QtWidgets.QLabel("INDICAÇÃO FISCAL:"),
                                "input": QtWidgets.QLineEdit()
                            }
                        }
        self.radial_input_dict = {
                    "arquitect_gender": {
                        "label": QtWidgets.QLabel("Gênero"),
                        "group": QtWidgets.QButtonGroup(),
                        "masculino": QtWidgets.QRadioButton("Masculino"),
                        "feminino": QtWidgets.QRadioButton("Feminino")
                    }
                }
        

    def populate(self):
        self.verticalLayout.addWidget(self.text_input_dict["stamp"]["label"])
        self.verticalLayout.addWidget(self.text_input_dict["stamp"]["input"])
        self.verticalLayout.addWidget(self.text_input_dict["arquitect"]["label"])
        self.verticalLayout.addWidget(self.text_input_dict["arquitect"]["input"])
        self.radial_input_dict["arquitect_gender"]["group"].addButton(self.radial_input_dict["arquitect_gender"]["masculino"])
        self.radial_input_dict["arquitect_gender"]["group"].addButton(self.radial_input_dict["arquitect_gender"]["feminino"])
        self.verticalLayout.addWidget(self.radial_input_dict["arquitect_gender"]["label"])
        self.verticalLayout.addWidget(self.radial_input_dict["arquitect_gender"]["feminino"])
        self.verticalLayout.addWidget(self.radial_input_dict["arquitect_gender"]["masculino"])
        self.verticalLayout.addWidget(self.text_input_dict["cau_code"]["label"])
        self.verticalLayout.addWidget(self.text_input_dict["cau_code"]["input"])
        self.verticalLayout.addWidget(self.text_input_dict["block"]["label"])
        self.verticalLayout.addWidget(self.text_input_dict["block"]["input"])
        self.verticalLayout.addWidget(self.text_input_dict["site_plan"]["label"])
        self.verticalLayout.addWidget(self.text_input_dict["site_plan"]["input"])
        self.verticalLayout.addWidget(self.text_input_dict["site_plan_code"]["label"])
        self.verticalLayout.addWidget(self.text_input_dict["site_plan_code"]["input"])
        self.verticalLayout.addWidget(self.text_input_dict["district"]["label"])
        self.verticalLayout.addWidget(self.text_input_dict["district"]["input"])
        self.verticalLayout.addWidget(self.text_input_dict["property_identifier"]["label"])
        self.verticalLayout.addWidget(self.text_input_dict["property_identifier"]["input"])

    def pre_set(self, data: GeneralInfoObject):
        self.text_input_dict["stamp"]["input"].setText(data.stamp)
        self.text_input_dict["arquitect"]["input"].setText(data.arquitect)
        self.radial_input_dict["arquitect_gender"][data.arquitect_gender.lower()].setChecked(True)
        self.text_input_dict["cau_code"]["input"].setText(data.cau_code)                
        self.text_input_dict["block"]["input"].setText(data.block)
        self.text_input_dict["site_plan"]["input"].setText(data.site_plan)
        self.text_input_dict["site_plan_code"]["input"].setText(data.site_plan_code)
        self.text_input_dict["district"]["input"].setText(data.district)
        self.text_input_dict["property_identifier"]["input"].setText(data.property_identifier)

    def as_general_info_object(self):
        return GeneralInfoObject(
            self.stamp, self.arquitect, self.arquitect_gender, self.cau_code, self.block, self.site_plan, self.site_plan_code, self.district, self.property_identifier
        )

    #auxiliary methods
    def get_text_input_result(self, key: str):
        return self.text_input_dict[key]["input"].text()

    def get_radial_input_result(self, key: str):
        return self.radial_input_dict[key]["group"].checkedButton().text()

    #properties
    @property
    def stamp(self):
        return self.get_text_input_result("stamp")
    @property
    def arquitect(self):
        return self.get_text_input_result("arquitect")
    @property
    def arquitect_gender(self):
        return self.get_radial_input_result("arquitect_gender")
    @property
    def cau_code(self):
        return self.get_text_input_result("cau_code")
    @property
    def block(self):
        return self.get_text_input_result("block")
    @property
    def site_plan(self):
        return self.get_text_input_result("site_plan")
    @property
    def site_plan_code(self):
        return self.get_text_input_result("site_plan_code")    
    @property
    def district(self):
        return self.get_text_input_result("district")
    @property
    def property_identifier(self):
        return self.get_text_input_result("property_identifier")