# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CriaMemorialDialog
                                 A QGIS plugin
 Teste de desenvolvimento para criação de memoriais de loteamento
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-07-30
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Eduardo C. Siqueira
        email                : eduardo.edu28@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtGui import QIcon
from .failed_validation_dialog import FailedValidationDialog
from ..models.data_classes import GeneralInfoObject
from ..models.enums import Gender, MemorialType
from ..models.user_settings import UserSettings
from ..paths import icon_path

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(
    os.path.join(
        os.path.dirname(__file__),
        'general_info_dialog_base.ui'),
    from_imports=True,
    import_from='cria_memorial')

class GeneralInfoDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, user_settings: UserSettings, parent=None):
        """Constructor."""
        super(GeneralInfoDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.setWindowIcon(QIcon(icon_path('aiG-icon')))
        for memorial_type in MemorialType:
            self.memorial_type_ComboBox.addItem(
                memorial_type.value,
                memorial_type
            )
        self.memorial_type_ComboBox.setCurrentIndex(-1)
        self.gender_btn_group = QtWidgets.QButtonGroup()
        self.gender_btn_group.addButton(self.female_radioButton)
        self.gender_btn_group.addButton(self.male_radioButton)
        self.user_settings = user_settings
        self.load_last_used()

    def load_last_used(self):
        self.architect_lineEdit.setText(self.user_settings.last_architect_name)
        self.cau_code_lineEdit.setText(self.user_settings.last_cau_code)
        match self.user_settings.last_architect_gender:
            case Gender.MALE:
                self.male_radioButton.setChecked(True)
            case Gender.FEMALE:
                self.female_radioButton.setChecked(True)
            case _:
                pass

    def accept(self):

        gender_selected = self.gender_btn_group.checkedButton() is not None
        memorial_type_selected = self.memorial_type_ComboBox.currentIndex() != -1

        warnings = []
        
        if not gender_selected or not memorial_type_selected:

            if not gender_selected:
                self.groupBox.setStyleSheet("color: red;")
                warnings.append("Gênero")

            if not memorial_type_selected:
                self.memorial_type_Label.setStyleSheet("color: red;")
                warnings.append("Tipo de memorial")

            FailedValidationDialog(*warnings).exec_()
            return

        else:

            self.user_settings.last_architect_gender = self.architect_gender
            self.user_settings.last_architect_name = self.architect
            self.user_settings.last_cau_code = self.cau_code
            super().accept()

    def as_general_info_object(self):

        print("architect_lineEdit:", self.architect_lineEdit)
        print("architect:", hasattr(self, "architect"))

        return GeneralInfoObject(
            self.stamp, self.architect, self.architect_gender, self.cau_code
        )

    def get_memorial_type(self) -> MemorialType:
        return self.memorial_type_ComboBox.currentData()

    #properties
    @property
    def stamp(self):
        return self.stamp_lineEdit.text()
    @property
    def architect(self):
        return self.architect_lineEdit.text()
    @property
    def architect_gender(self):
        return Gender(self.gender_btn_group.checkedButton().text())
    @property
    def cau_code(self):
        return self.cau_code_lineEdit.text()