# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CriaMemorialDialog
                                 A QGIS plugin
 Teste de desenvolvimento para criação de memoriais de loteamento
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-07-30
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Eduardo C. Siqueira
        email                : eduardo.edu28@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from ..models.data_classes import MainParcelDialogResult
from ..models.basic_parcel import BasicParcel

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(
    os.path.join(
        os.path.dirname(__file__),
        'main_parcel_dialog_base.ui'),
    from_imports=True,
    import_from='cria_memorial')


class MainParcelDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parcel: BasicParcel, parent=None):
        """Constructor."""
        super(MainParcelDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.parcel = parcel
        self.finished.connect(self.clean_highlight)
        parcel.feature_context.layer.select(parcel.feature_context.feature.id())

        self.main_label.setText(f"Complemente as informações do lote principal ({parcel.name})")

        self.street_side_btn_group = QtWidgets.QButtonGroup()
        self.street_side_btn_group.addButton(self.even_numbered_side_radioButton)
        self.street_side_btn_group.addButton(self.odd_numbered_side_radioButton)

        self.shape_btn_group = QtWidgets.QButtonGroup()
        self.shape_btn_group.addButton(self.regular_shape_radioButton)
        self.shape_btn_group.addButton(self.irregular_shape_radioButton)


    def get_result(self) -> MainParcelDialogResult:
        return MainParcelDialogResult(
            self.street_side_btn_group.checkedButton().text(),
            self.main_street_name_lineEdit.text(),
            self.main_street_code_lineEdit.text(),
            self.number_lineEdit.text(),
            self.shape_btn_group.checkedButton().text(),
            self.distance_to_corner_lineEdit.text(),
            self.cross_street_name_lineEdit.text(),
            self.cross_street_code_lineEdit.text(),
            self.property_identifier_lineEdit.text()
        ) or None

    def clean_highlight(self):
        self.parcel.feature_context.layer.removeSelection()