# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CriaMemorialDialog
                                 A QGIS plugin
 Teste de desenvolvimento para criação de memoriais de loteamento
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-07-30
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Eduardo C. Siqueira
        email                : eduardo.edu28@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.core import QgsPalLayerSettings, QgsVectorLayerSimpleLabeling, Qgis

from ..models.data_classes import SidesWidgetResult
from ..models.segment import Segment
from .failed_validation_dialog import FailedValidationDialog

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(
    os.path.join(
        os.path.dirname(__file__),
        'sides_definition_wizard_base.ui'),
    from_imports=True,
    import_from='cria_memorial')


class SidesDefinitionWizard(QtWidgets.QWizard, FORM_CLASS):
    def __init__(self, segments: list[Segment], parent=None):
        """Constructor."""
        super(SidesDefinitionWizard, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.segments = segments
        self.segment_dict = {segment.name: segment for segment in self.segments}
        self.segment_names = list(self.segment_dict)
        self.reordered_segment_list = segments
        self.reference_layer = segments[0].feature_context.layer
        self.consider_4_sides = True
        self.__side_field_name__ = 'side'
        self.setupUi(self)
        self.comboboxes = {
            "side_1_start": self.side_1_comboBox, 
            "side_1_end": self.side_1_comboBox_2, 
            "side_2_start": self.side_2_comboBox, 
            "side_2_end": self.side_2_comboBox_2, 
            "side_3_start": self.side_3_comboBox, 
            "side_3_end": self.side_3_comboBox_2, 
            "side_4_start": self.side_4_comboBox,
            "side_4_end": self.side_4_comboBox_2
        }
        self.label_segments()
        self.reference_layer.startEditing()
        self._connect_signals()

    #
    #
    # trigger para esconder/mostrar Fundos na segunda pagina
    def reset_page_2(self):

        current_selection = self.sides_quant_comboBox.currentText()
        selected_4_sides = current_selection == "4 LADOS: FRENTE, DIREITA, FUNDOS, ESQUERDA"
        selection_has_changed = selected_4_sides != self.consider_4_sides

        if selection_has_changed:
            self.clear_layer_sides()

            for combobox in self.comboboxes.values():
                combobox.clear()

            self.side_1_comboBox.addItems(self.segment_names)
            self.side_1_comboBox.setCurrentIndex(-1)

            if selected_4_sides:
                self.side_4_label.setVisible(True)
                self.side_4_comboBox.setVisible(True)
                self.side_4_comboBox_2.setVisible(True)
                self.up_to_label_4.setVisible(True)
                self.side_3_label.setText("FUNDOS")
                self.consider_4_sides = True
            else:
                self.side_4_label.setVisible(False)
                self.side_4_comboBox.setVisible(False)
                self.side_4_comboBox_2.setVisible(False)
                self.up_to_label_4.setVisible(False)
                self.side_3_label.setText("DIREITA")
                self.consider_4_sides = False

            self.reference_layer.triggerRepaint()

    # trigger para ajustes após seleção de frente:
    def on_side_1_start_selection_changed(self):
        selected_segment = self.segment_from_combobox(self.comboboxes["side_1_start"])
        #    - ajustar lista de segmentos de acordo
        segment_index = self.segments.index(selected_segment)
        self.reordered_segment_list = self.segments[segment_index:] + self.segments[:segment_index]
        #   - habilitar segundo combobox com opções restantes
        self.reload_combobox("side_1_end", self.reordered_segment_list, -1)
        #   - zerar escolhas dos outros combobox e deixar habilitado apenas frente e direita
        self.clear_remaining_comboboxes("side_2_start")
        self.clear_layer_sides()

    def on_side_1_end_selection_changed(self):

        selected_segment = self.segment_from_combobox(self.comboboxes["side_1_end"])
        #    - ajustar lista de segmentos de acordo
        segment_index = self.reordered_segment_list.index(selected_segment)
        remaining_segments = self.reordered_segment_list[segment_index + 1:]
        #   - habilitar próximo combobox com opções restantes
        self.reload_combobox("side_2_start", remaining_segments, 0)
        self.reload_combobox("side_2_end", remaining_segments, -1)
        #   - zerar escolhas dos outros combobox e deixar habilitado apenas frente e direita
        self.clear_remaining_comboboxes("side_3_start")

        #   - zerar atributos de feature dos outros segmentos, e deixar apenas o selecionado como "front"
        self.clear_layer_sides()
        self.side_1_range = self.get_segment_range("side_1")
        self.update_features_side_attribute(self.side_1_range, "front")

        self.reference_layer.triggerRepaint()

    # trigger para ajustes após seleção de Direita:
    def on_side_2_start_selection_changed(self):

        selected_segment = self.segment_from_combobox(self.comboboxes["side_2_start"])

        #   - ajustar lista de segmentos de acordo
        selected_segment_index = self.reordered_segment_list.index(selected_segment)
        remaining_segments = self.reordered_segment_list[selected_segment_index:]

        # verificar consistência com seleção anterior e ajustar:
        side_1_last_segment = self.segment_from_combobox(self.comboboxes["side_1_end"])
        expected_last_segment = self.reordered_segment_list[selected_segment_index - 1]

        if expected_last_segment != side_1_last_segment:
            self.comboboxes["side_1_end"].setCurrentText(expected_last_segment.name)
            self.side_1_range = self.get_segment_range("side_1")
            self.update_features_side_attribute(self.side_1_range, "front")
            self.reload_combobox("side_2_start", remaining_segments, 0)

        self.reload_combobox("side_2_end", remaining_segments, -1)

        #   - zerar atributos de features que não sejam "front"
        self.update_features_side_attribute(remaining_segments, "undefined")
        #   - redefinir comboBoxes seguintes
        self.clear_remaining_comboboxes("side_3_start")

        self.reference_layer.triggerRepaint()

    def on_side_2_end_selection_changed(self):

        selected_segment = self.segment_from_combobox(self.comboboxes["side_2_end"])
        #    - ajustar lista de segmentos de acordo
        segment_index = self.reordered_segment_list.index(selected_segment)
        remaining_segments = self.reordered_segment_list[segment_index + 1:]
        #   - habilitar próximo combobox com opções restantes
        self.reload_combobox("side_3_start", remaining_segments, 0)
        self.reload_combobox("side_3_end", remaining_segments, -1)
        #   - zerar escolhas dos outros combobox e deixar habilitado apenas frente e direita
        self.clear_remaining_comboboxes("side_4_start")

        #   - zerar atributos de feature dos outros segmentos que nao sejam "front" e "left"
        
        self.side_2_range = self.get_segment_range("side_2")
        self.update_features_side_attribute(self.side_2_range, "left")
        self.update_features_side_attribute(remaining_segments,"undefined")

        self.reference_layer.triggerRepaint()

    # trigger para ajustes após seleção de comboBox 3
    def on_side_3_start_selection_changed(self):

        selected_segment = self.segment_from_combobox(self.comboboxes["side_3_start"])
        #   - ajustar lista de segmentos de acordo
        selected_segment_index = self.reordered_segment_list.index(selected_segment)
        remaining_segments = self.reordered_segment_list[selected_segment_index:]

        # verificar consistência com seleção anterior e ajustar:
        side_2_last_segment = self.segment_from_combobox(self.comboboxes["side_2_end"])
        expected_last_segment = self.reordered_segment_list[selected_segment_index - 1]

        if expected_last_segment != side_2_last_segment:
            self.comboboxes["side_2_end"].setCurrentText(expected_last_segment.name)
            self.side_2_range = self.get_segment_range("side_2")
            self.update_features_side_attribute(self.side_2_range, "left")
            self.reload_combobox("side_3_start", remaining_segments, 0)

        self.reload_combobox("side_3_end", remaining_segments, -1)

        #   - zerar atributos de features que não sejam "front" ou "left"
        self.update_features_side_attribute(remaining_segments, "undefined")
        #   - redefinir comboboxes seguintes
        self.clear_remaining_comboboxes("side_4_start")

        self.reference_layer.triggerRepaint()

    def on_side_3_end_selection_changed(self):

        self.side_3_range = self.get_segment_range("side_3")

        # SE 4 LADOS:
        if self.consider_4_sides:
            #    - ajustar lista de segmentos de acordo
            selected_segment = self.segment_from_combobox(self.comboboxes["side_3_end"])
            selected_segment_index = self.reordered_segment_list.index(selected_segment)
            remaining_segments = self.reordered_segment_list[selected_segment_index + 1:]
            #   - habilitar combobox Direita com opções restantes
            self.reload_combobox("side_4_start", remaining_segments, 0)
            self.reload_combobox("side_4_end", remaining_segments, -1)
            #   - zerar atributos de feature dos outros segmentos que nao sejam "front", "left" ou "back"
            self.update_features_side_attribute(self.side_3_range, "back")
            self.update_features_side_attribute(remaining_segments,"undefined")
        else:
            self.update_features_side_attribute(self.side_3_range, "right")

        self.reference_layer.triggerRepaint()

    # trigger para ajustes após seleção de comboBox 4
    def on_side_4_start_selection_changed(self):

        selected_segment = self.segment_from_combobox(self.comboboxes["side_4_start"])
        #   - ajustar lista de segmentos de acordo
        selected_segment_index = self.reordered_segment_list.index(selected_segment)
        remaining_segments = self.reordered_segment_list[selected_segment_index:]

        # verificar consistência com seleção anterior e ajustar:
        side_3_last_segment = self.segment_from_combobox(self.comboboxes["side_3_end"])
        expected_last_segment = self.reordered_segment_list[selected_segment_index - 1]

        if expected_last_segment != side_3_last_segment:
            self.comboboxes["side_3_end"].setCurrentText(expected_last_segment.name)
            self.side_3_range = self.get_segment_range("side_3")
            self.update_features_side_attribute(self.side_3_range, "back")
            self.reload_combobox("side_4_start", remaining_segments, 0)

        self.reload_combobox("side_4_end", remaining_segments, -1)

        #   - zerar atributos de features que não sejam "front", "left" ou "back"
        self.update_features_side_attribute(remaining_segments, "undefined")

        self.reference_layer.triggerRepaint()

    def on_side_4_end_selection_changed(self):

        self.side_4_range = self.get_segment_range("side_4")
        self.update_features_side_attribute(self.side_4_range, "right")

        self.reference_layer.triggerRepaint()

    def validateCurrentPage(self):
        if self.currentPage().isFinalPage():
            for index, combobox in enumerate(self.comboboxes.values(), 1):
                if self.consider_4_sides is False and (index == 7 or index == 8):
                    continue
                elif combobox.currentIndex() == -1:
                    FailedValidationDialog().exec_()
                    return False
            return True
        elif self.sides_quant_comboBox.currentIndex() == -1:
            FailedValidationDialog().exec_()
            return False
        else:
            return True

    def _connect_signals(self):

        self.rejected.connect(self.quit)

        self.accepted.connect(self.finish)

        self.currentIdChanged.connect(self.reset_page_2)

        self.side_1_comboBox.activated.connect(self.on_side_1_start_selection_changed)
        self.side_1_comboBox_2.activated.connect(self.on_side_1_end_selection_changed)
        self.side_2_comboBox.activated.connect(self.on_side_2_start_selection_changed)
        self.side_2_comboBox_2.activated.connect(self.on_side_2_end_selection_changed)
        self.side_3_comboBox.activated.connect(self.on_side_3_start_selection_changed)
        self.side_3_comboBox_2.activated.connect(self.on_side_3_end_selection_changed)
        self.side_4_comboBox.activated.connect(self.on_side_4_start_selection_changed)
        self.side_4_comboBox_2.activated.connect(self.on_side_4_end_selection_changed)

    def label_segments(self):
        settings = QgsPalLayerSettings()
        settings.fieldName = "name"
        settings.placement = Qgis.LabelPlacement.Line
        self.reference_layer.setLabeling(QgsVectorLayerSimpleLabeling(settings))
        self.reference_layer.setLabelsEnabled(True)
        self.reference_layer.triggerRepaint()

    def get_result(self):

        if self.consider_4_sides:
            return SidesWidgetResult(
                self.side_1_range, 
                self.side_2_range, 
                self.side_4_range,
                self.side_3_range, 
            )
        else:
            return SidesWidgetResult(
                self.side_1_range, 
                self.side_2_range, 
                self.side_3_range, 
            )

    def quit(self):
        self.reference_layer.rollBack()

    def finish(self):
        self.reference_layer.commitChanges()


# aux functions
    def segment_from_combobox(self, combobox) -> Segment:
        name = combobox.currentText()
        return self.segment_dict[name]

    def reload_combobox(self, cb_key: str, segment_list: list[Segment], set_index: int):
        self.comboboxes[cb_key].clear()
        self.comboboxes[cb_key].addItems([segment.name for segment in segment_list])
        self.comboboxes[cb_key].setCurrentIndex(set_index)

    def clear_remaining_comboboxes(self, first_to_clear_key: str):

        key_list = list(self.comboboxes)
        first_to_clear_index = key_list.index(first_to_clear_key)
        combobox_list = list(self.comboboxes.values())

        for combobox in combobox_list[first_to_clear_index:]:
            combobox.clear()

    def update_features_side_attribute(self, segments: list[Segment], side_name: str):
        for segment in segments:
            feature = segment.feature_context.feature
            feature[self.__side_field_name__] = side_name
            self.reference_layer.updateFeature(feature)

    def reset_layer_sides(self, sides: list[str]):
        for feature in self.reference_layer.getFeatures():
            if sides.__contains__(feature[self.__side_field_name__]):
                feature[self.__side_field_name__] = "undefined"
                self.reference_layer.updateFeature(feature)

    def clear_layer_sides(self):
        for feature in self.reference_layer.getFeatures():
            feature[self.__side_field_name__] = "undefined"
            self.reference_layer.updateFeature(feature)

    def get_segment_range(self, cb_key_prefix: str) -> list[Segment]:
        start_segment = self.segment_from_combobox(self.comboboxes[cb_key_prefix+"_start"])
        end_segment = self.segment_from_combobox(self.comboboxes[cb_key_prefix + "_end"])
        start_segment_index = self.reordered_segment_list.index(start_segment)
        end_segment_index = self.reordered_segment_list.index(end_segment)

        return self.reordered_segment_list[start_segment_index:end_segment_index+1]
