# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CriaMemorialDialog
                                 A QGIS plugin
 Teste de desenvolvimento para criação de memoriais de loteamento
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-07-30
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Eduardo C. Siqueira
        email                : eduardo.edu28@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from ..models.data_classes import GeneralInfoObject
from ..models.complements import Side
from .street_confrontations_widget import StreetConfrontationsWidget

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(
    os.path.join(
        os.path.dirname(__file__),
        'street_confrontations_tabwidget_container_base.ui'),
    from_imports=True,
    import_from='cria_memorial')

class StreetConfrontationsTabWidgetContainer(QtWidgets.QTabWidget, FORM_CLASS):
    def __init__(self, side: Side, parent=None):
        """Constructor."""
        super(StreetConfrontationsTabWidgetContainer, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.side = side
        self.tabs: dict[str, StreetConfrontationsWidget] = {}
        self.setupUi(self)
        self.create_tabs()

    def create_tabs(self):
        self.tabWidget.clear()

        for segment in self.side.segments:
            self.tabs[segment.name] = StreetConfrontationsWidget()

        for name, widget in self.tabs.items():
            self.tabWidget.addTab(widget, name)