# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CriaMemorialDialog
                                 A QGIS plugin
 Teste de desenvolvimento para criação de memoriais de loteamento
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-07-30
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Eduardo C. Siqueira
        email                : eduardo.edu28@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtGui import QIcon
from ..models.complements import Side, Street, Front
from .street_confrontations_tabwidget_container import StreetConfrontationsTabWidgetContainer #tabs s.name: tab
from ..paths import icon_path

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(
    os.path.join(
        os.path.dirname(__file__),
        'street_confrontations_dialog_base.ui'),
    from_imports=True,
    import_from='cria_memorial')

class StreetConfrontationsDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, sides: list[Side], parent=None):
        """Constructor."""
        super(StreetConfrontationsDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.sides = sides
        self.pages: dict[Side, StreetConfrontationsTabWidgetContainer] = {}
        self.setupUi(self)
        self.setWindowIcon(QIcon(icon_path('aiG-icon')))
        self.create_pages()
        self.comboBox.currentIndexChanged.connect(self.select_page)

    def create_pages(self):

        for side in self.sides:
            self.pages[side] = StreetConfrontationsTabWidgetContainer(side)

        for index, pair in enumerate(self.pages.items()):
            side, page = pair
            self.stackedWidget.insertWidget(index, page)
            self.comboBox.insertItem(index, side.name)
            if isinstance(side, Front):
                page.tabs[side.segments[0].name].street_name_lineEdit.setText(side.street.name)
                page.tabs[side.segments[0].name].street_code_lineEdit.setText(side.street.code)
        

    def select_page(self):

        index = self.comboBox.currentIndex()
        self.stackedWidget.setCurrentIndex(index)

    def process_results(self):
        
        for side, page in self.pages.items():
            for segment_name, tab in page.tabs.items():
                street_name = tab.street_name_lineEdit.text()
                if street_name.strip() != "":
                    code = tab.street_code_lineEdit.text().strip()
                    street_description = f"{street_name} ({code})" if code else street_name
                    segment = next(
                        segment for segment in side.segments
                        if segment.name == segment_name
                    )
                    segment.set_street_confrontations([street_description])

    #TODO: implementar validações
    def accept(self):
        self.process_results()
        super().accept()