# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CriaMemorialDialog
                                 A QGIS plugin
 Teste de desenvolvimento para criação de memoriais de loteamento
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-07-30
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Eduardo C. Siqueira
        email                : eduardo.edu28@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtGui import QIcon

from ..paths import icon_path
from ..models.user_settings import UserSettings
from ..models.enums import DocumentFormat

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(
    os.path.join(
        os.path.dirname(__file__),
        'user_settings_dialog_base.ui'),
    from_imports=True,
    import_from='cria_memorial')

class UserSettingsDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, user_settings: UserSettings, parent=None):
        """Constructor."""
        super(UserSettingsDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.format_preference_btn_group = QtWidgets.QButtonGroup()
        self.format_preference_btn_group.addButton(self.pdf_default_radioButton)
        self.format_preference_btn_group.addButton(self.docx_default_radioButton)
        self.setWindowIcon(QIcon(icon_path('aiG-icon')))
        self.user_settings = user_settings
        self.atc_logo_QgsFileWidget.setFilter(DocumentFormat.IMAGE.filter)
        self.main_logo_QgsFileWidget.setFilter(DocumentFormat.IMAGE.filter)
        self.load_settings()
        self.accepted.connect(self.save_settings)

    def load_settings(self):

        match self.user_settings.output_doc_format_preference:

            case DocumentFormat.PDF:
                self.pdf_default_radioButton.setChecked(True)
        
            case DocumentFormat.DOCX:
                self.docx_default_radioButton.setChecked(True)
        
        self.atc_logo_QgsFileWidget.setFilePath(self.user_settings.atc_logo_path)
        self.main_logo_QgsFileWidget.setFilePath(self.user_settings.main_logo_path)
        self.docx_template_QgsFileWidget.setFilePath(self.user_settings.docx_template_path)

    def save_settings(self):

        match self.format_preference_btn_group.checkedButton():

            case self.pdf_default_radioButton:
                self.user_settings.output_doc_format_preference = DocumentFormat.PDF

            case self.docx_default_radioButton:
                self.user_settings.output_doc_format_preference = DocumentFormat.DOCX

        self.user_settings.atc_logo_path = self.atc_logo_QgsFileWidget.filePath()
        self.user_settings.main_logo_path = self.main_logo_QgsFileWidget.filePath()
        self.user_settings.docx_template_path = self.docx_template_QgsFileWidget.filePath()
