# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CriaMemorialDialog
                                 A QGIS plugin
 Teste de desenvolvimento para criação de memoriais de loteamento
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-07-30
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Eduardo C. Siqueira
        email                : eduardo.edu28@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from ..models.data_classes import GeneralInfoObject
from .failed_validation_dialog import FailedValidationDialog

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(
    os.path.join(
        os.path.dirname(__file__),
        'general_info_dialog_base.ui'),
    from_imports=True,
    import_from='cria_memorial')

#TODO: Refazer sem ser dinâmico
class GeneralInfoDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(GeneralInfoDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.prepare_inputs()
        self.populate()

    def prepare_inputs(self):
        self.text_input_dict = {
                            "stamp": {
                                "label": QtWidgets.QLabel("TÍTULO DO CARIMBO DA PRANCHA DE PROJETO DE LOTEAMENTO APROVADO:"),
                                "input": QtWidgets.QLineEdit()
                            },
                            "architect":{
                                "label": QtWidgets.QLabel("ARQUITETA/ARQUITETO:"),
                                "input": QtWidgets.QLineEdit()
                            },
                            "cau_code":{
                                "label": QtWidgets.QLabel("CAU:"),
                                "input": QtWidgets.QLineEdit()
                            },
                        }
        self.radial_input_dict = {
                    "architect_gender": {
                        "label": QtWidgets.QLabel("Gênero*"),
                        "group": QtWidgets.QButtonGroup(),
                        "masculino": QtWidgets.QRadioButton("&Masculino"),
                        "feminino": QtWidgets.QRadioButton("&Feminino")
                    }
                }
        

    def populate(self):
        self.verticalLayout.addWidget(self.text_input_dict["stamp"]["label"])
        self.verticalLayout.addWidget(self.text_input_dict["stamp"]["input"])
        self.verticalLayout.addWidget(self.text_input_dict["architect"]["label"])
        self.verticalLayout.addWidget(self.text_input_dict["architect"]["input"])
        self.radial_input_dict["architect_gender"]["group"].addButton(self.radial_input_dict["architect_gender"]["masculino"])
        self.radial_input_dict["architect_gender"]["group"].addButton(self.radial_input_dict["architect_gender"]["feminino"])
        self.verticalLayout.addWidget(self.radial_input_dict["architect_gender"]["label"])
        self.verticalLayout.addWidget(self.radial_input_dict["architect_gender"]["feminino"])
        self.verticalLayout.addWidget(self.radial_input_dict["architect_gender"]["masculino"])
        self.verticalLayout.addWidget(self.text_input_dict["cau_code"]["label"])
        self.verticalLayout.addWidget(self.text_input_dict["cau_code"]["input"])

    def pre_set(self, data: GeneralInfoObject):
        self.text_input_dict["stamp"]["input"].setText(data.stamp)
        self.text_input_dict["architect"]["input"].setText(data.architect)
        self.radial_input_dict["architect_gender"][data.architect_gender.lower()].setChecked(True)
        self.text_input_dict["cau_code"]["input"].setText(data.cau_code)                

    def accept(self):
        if self.radial_input_dict["architect_gender"]["group"].checkedButton() is None:
            self.radial_input_dict["architect_gender"]["label"].setStyleSheet("color: red;")
            FailedValidationDialog("Gênero").exec_()
            return
        else:
            super().accept()

    def as_general_info_object(self):
        return GeneralInfoObject(
            self.stamp, self.architect, self.architect_gender, self.cau_code
        )

    #auxiliary methods
    def get_text_input_result(self, key: str):
        return self.text_input_dict[key]["input"].text()

    def get_radial_input_result(self, key: str):
        return self.radial_input_dict[key]["group"].checkedButton().text().replace("&","")

    #properties
    @property
    def stamp(self):
        return self.get_text_input_result("stamp")
    @property
    def architect(self):
        return self.get_text_input_result("architect")
    @property
    def architect_gender(self):
        return self.get_radial_input_result("architect_gender")
    @property
    def cau_code(self):
        return self.get_text_input_result("cau_code")
    