# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CriaMemorialDialog
                                 A QGIS plugin
 Teste de desenvolvimento para criação de memoriais de loteamento
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-07-30
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Eduardo C. Siqueira
        email                : eduardo.edu28@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.core import QgsPalLayerSettings, QgsVectorLayerSimpleLabeling, Qgis

from ..models.data_classes import SidesWidgetResult
from ..models.segment import Segment
from .failed_validation_dialog import FailedValidationDialog

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(
    os.path.join(
        os.path.dirname(__file__),
        'sides_definition_wizard_base.ui'),
    from_imports=True,
    import_from='cria_memorial')


class SidesDefinitionWizard(QtWidgets.QWizard, FORM_CLASS):
    def __init__(self, segments: list[Segment], parent=None):
        """Constructor."""
        super(SidesDefinitionWizard, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.segments = segments
        self.segment_dict = {segment.name: segment for segment in self.segments}
        self.segment_names = list(self.segment_dict.keys())
        self.reordered_segment_list = segments
        self.reference_layer = segments[0].feature_context.layer
        self.selections = [None, None, None, None]
        self.consider_4_sides = True
        self.__side_field_name__ = 'side'
        self.setupUi(self)
        self.comboboxes = [self.side_1_comboBox, self.side_2_comboBox, self.side_3_comboBox, self.side_4_comboBox]
        self.label_segments()
        self.reference_layer.startEditing()
        self._connect_signals()

    #
    #
    # trigger para esconder/mostrar Fundos na segunda pagina
    def reset_page_2(self):
        current_selection = self.sides_quant_comboBox.currentText()
        current_selection_is_4_sides = current_selection == "4 LADOS: FRENTE, DIREITA, FUNDOS, ESQUERDA"
        selection_has_changed = current_selection_is_4_sides != self.consider_4_sides
        if selection_has_changed:
            self.clear_layer_sides()
            for combobox in self.comboboxes:
                combobox.clear()
            self.side_1_comboBox.addItems(self.segment_names)
            self.side_1_comboBox.setCurrentIndex(-1)
            if current_selection_is_4_sides:
                self.side_4_label.setVisible(True)
                self.side_4_comboBox.setVisible(True)
                self.side_3_label.setText("FUNDOS")
                self.consider_4_sides = True
            else:
                self.side_4_label.setVisible(False)
                self.side_4_comboBox.setVisible(False)
                self.side_3_label.setText("ESQUERDA")
                self.consider_4_sides = False
            self.reference_layer.triggerRepaint()

    # trigger para ajustes após seleção de frente:
    def side_1_selection_changed(self):
        selected_segment = self.segment_from_combobox(self.side_1_comboBox)
        #    - ajustar lista de segmentos de acordo
        segment_index = self.segments.index(selected_segment)
        self.reordered_segment_list = self.segments[segment_index:] + self.segments[:segment_index]
        #   - habilitar segundo combobox com opções restantes
        self.side_2_comboBox.clear()
        self.side_2_comboBox.addItems([segment.name for segment in self.reordered_segment_list[1:]])
        self.side_2_comboBox.setCurrentIndex(-1)
        #   - zerar escolhas dos outros combobox e deixar habilitado apenas frente e direita
        self.side_3_comboBox.clear()
        self.side_4_comboBox.clear()
        #   - zerar atributos de feature dos outros segmentos, e deixar apenas o selecionado como "front"
        self.clear_layer_sides()
        selected_feature =  selected_segment.feature_context.feature
        selected_feature[self.__side_field_name__] = "front"
        self.reference_layer.updateFeature(selected_feature)
        self.selections[0] = selected_segment
        self.selections[1] = None
        self.selections[2] = None
        self.selections[3] = None
        self.reference_layer.triggerRepaint()

    # trigger para ajustes após seleção de Direita:
    def side_2_selection_changed(self):
        selected_segment = self.segment_from_combobox(self.side_2_comboBox)
        #   - ajustar lista de segmentos de acordo
        segment_index = self.reordered_segment_list.index(selected_segment)
        remaining_segments = self.reordered_segment_list[segment_index + 1:]
        #   - atualizar atributos dos features de "front"
        self.update_features_side_attribute(self.reordered_segment_list[:segment_index], "front")
        #   - atualizar atributo do feature selecionado para "right"
        selected_feature = selected_segment.feature_context.feature
        selected_feature[self.__side_field_name__] = "right"
        self.reference_layer.updateFeature(selected_feature)
        #   - zerar atributos de features que não sejam "front" ou "right"
        self.update_features_side_attribute(remaining_segments, "undefined")
        #   - redefinir comboBoxes seguintes
        self.side_3_comboBox.clear()
        self.side_4_comboBox.clear()
        #   - habilitar opções no combobox 3
        self.side_3_comboBox.addItems([segment.name for segment in remaining_segments])
        self.side_3_comboBox.setCurrentIndex(-1)
        self.selections[1] = selected_segment
        self.selections[2] = None
        self.selections[3] = None
        self.reference_layer.triggerRepaint()

    # trigger para ajustes após seleção de comboBox 3
    def side_3_selection_changed(self):
        selected_segment = self.segment_from_combobox(self.side_3_comboBox)
        #   - ajustar lista de segmentos de acordo
        segment_index = self.reordered_segment_list.index(selected_segment)
        remaining_segments = self.reordered_segment_list[segment_index + 1:]        
        #   - atualizar atributos dos features de "right"
        right_side_segments = self.reordered_segment_list[self.reordered_segment_list.index(self.selections[1]):self.reordered_segment_list.index(selected_segment)]
        self.update_features_side_attribute(right_side_segments, "right")
        # SE 4 LADOS:
        if self.consider_4_sides:
            #   - atualizar atributo do feature selecionado para "back"
            selected_feature = selected_segment.feature_context.feature
            selected_feature[self.__side_field_name__] = "back"
            self.reference_layer.updateFeature(selected_feature)
            #   - zerar atributos de features que sejam "left"
            remaining_segments = self.reordered_segment_list[self.reordered_segment_list.index(selected_segment)+1:]
            self.update_features_side_attribute(remaining_segments, "undefined")
            #   - habilitar combobox Esquerda com opções restantes
            self.side_4_comboBox.clear()
            self.side_4_comboBox.addItems([segment.name for segment in remaining_segments])
            self.side_4_comboBox.setCurrentIndex(-1)
        else:
            self.update_features_side_attribute(
                self.reordered_segment_list[self.reordered_segment_list.index(selected_segment):],
                "left"
            )
        self.selections[2] = selected_segment
        self.selections[3] = None
        self.reference_layer.triggerRepaint()

    # trigger para ajustes após seleção de comboBox 4
    def side_4_selection_changed(self):
        selected_segment = self.segment_from_combobox(self.side_4_comboBox)
        #   - atualizar atributos dos features de "back"
        back_side_segments = self.reordered_segment_list[self.reordered_segment_list.index(self.selections[2]):self.reordered_segment_list.index(selected_segment)]
        self.update_features_side_attribute(back_side_segments, "back")
        #   - atualizar atributos dos features de left
        left_side_segments = self.reordered_segment_list[self.reordered_segment_list.index(selected_segment):]
        self.update_features_side_attribute(left_side_segments, "left")
        self.selections[3] = selected_segment
        self.reference_layer.triggerRepaint()

    def validateCurrentPage(self):
        if self.currentPage().isFinalPage():
            for index, combobox in enumerate(self.comboboxes, 1):
                if self.consider_4_sides is False and index == 4:
                    continue
                elif combobox.currentIndex() == -1:
                    FailedValidationDialog().exec_()
                    return False
            return True
        elif self.sides_quant_comboBox.currentIndex() == -1:
            FailedValidationDialog().exec_()
            return False
        else:
            return True

    def _connect_signals(self):
        self.rejected.connect(self.quit)
        self.accepted.connect(self.finish)
        self.currentIdChanged.connect(self.reset_page_2)
        self.side_1_comboBox.activated.connect(self.side_1_selection_changed)
        self.side_2_comboBox.activated.connect(self.side_2_selection_changed)
        self.side_3_comboBox.activated.connect(self.side_3_selection_changed)
        self.side_4_comboBox.activated.connect(self.side_4_selection_changed)

    def getResult(self):
        side_2_start_index = self.reordered_segment_list.index(self.selections[1])
        side_3_start_index = self.reordered_segment_list.index(self.selections[2])
        front_side_segments = self.reordered_segment_list[:side_2_start_index]
        right_side_segments = self.reordered_segment_list[side_2_start_index:side_3_start_index]
        if self.consider_4_sides:
            side_4_start_index = self.reordered_segment_list.index(self.selections[3])
            back_side_segments = self.reordered_segment_list[side_3_start_index:side_4_start_index]
            left_side_segments = self.reordered_segment_list[side_4_start_index:]

            return SidesWidgetResult(
                front_side_segments, 
                right_side_segments, 
                left_side_segments, 
                back_side_segments,
            )
        else:
            left_side_segments = self.reordered_segment_list[side_3_start_index:]
            return SidesWidgetResult(
                front_side_segments,
                right_side_segments,
                left_side_segments,
            )


    #TODO: ajustar clean_highlights
    def clean_highlights(self):
        for sg in self.segments:
            sg.feature_context.layer.removeSelection()

    def quit(self):
        self.clean_highlights()
        self.reference_layer.rollBack()

    def finish(self):
        self.reference_layer.commitChanges()

    def segment_from_combobox(self, combobox) -> Segment:
        name = combobox.currentText()
        return self.segment_dict[name]

    def update_features_side_attribute(self, segments: list[Segment], side_name: str):
        for segment in segments:
            feature = segment.feature_context.feature
            feature[self.__side_field_name__] = side_name
            self.reference_layer.updateFeature(feature)

    def reset_layer_sides(self, sides: list[str]):
        for feature in self.reference_layer.getFeatures():
            if sides.__contains__(feature[self.__side_field_name__]):
                feature[self.__side_field_name__] = "undefined"
                self.reference_layer.updateFeature(feature)

    def clear_layer_sides(self):
        for feature in self.reference_layer.getFeatures():
            feature[self.__side_field_name__] = "undefined"
            self.reference_layer.updateFeature(feature)

    def label_segments(self):
        settings = QgsPalLayerSettings()
        settings.fieldName = "name"
        settings.placement = Qgis.LabelPlacement.Line
        self.reference_layer.setLabeling(QgsVectorLayerSimpleLabeling(settings))
        self.reference_layer.setLabelsEnabled(True)
        self.reference_layer.triggerRepaint()